name: Crystal CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.0.0

    steps:
    - uses: actions/checkout@v1

    - name: Install LibRocksDB
      run: |
        apt-get update && \
        apt-get install wget libgflags2.2 libsnappy1v5 -y && \
        wget https://launchpad.net/~hnakamur/+archive/ubuntu/rocksdb/+files/librocksdb6.5_6.7.3-1ppa1~bionic_amd64.deb && \
        wget https://launchpad.net/~hnakamur/+archive/ubuntu/rocksdb/+files/librocksdb-dev_6.7.3-1ppa1~bionic_amd64.deb && \
        apt install ./librocksdb6.5_6.7.3-1ppa1~bionic_amd64.deb -y && \
        apt install ./librocksdb-dev_6.7.3-1ppa1~bionic_amd64.deb -y

    - name: Install dependencies from shards
      run: shards install

    - name: Build librocksdb.o
      run: c++ -fno-rtti -c src/librocksdb.cc -o src/librocksdb.o

    - name: Run tests
      run: crystal spec

    - name: Check format
      run: crystal tool format --check
