name: Crystal CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.32.1

    steps:
    - uses: actions/checkout@v1

    - name: Install LibRocksDB
      run: |
        apt-get update && \
        apt install debian-archive-keyring && \
        ln -s /usr/share/keyrings/debian-archive*.gpg /etc/apt/trusted.gpg.d/ && \
        echo "deb http://httpredir.debian.org/debian/ buster main contrib non-free" >> /etc/apt/sources.list && \
        apt-get update && \
        apt-get install librocksdb-dev -y

    - name: Install dependencies from shards
      run: shards install

    - name: Build librocksdb.o
      run: c++ -fno-rtti -c src/librocksdb.cc -o src/librocksdb.o

    - name: Run tests
      run: crystal spec

    - name: Check format
      run: crystal tool format --check
